[package]
name = "eval"
version = "0.1.0"
authors = ["Patrick Heck <49785565+FitzOReilly@users.noreply.github.com>"]
edition = "2021"

[dependencies]
movegen = { path = "../movegen" }

[features]
trace = []

[dev-dependencies]
rand = "0.9.2"
