[package]
name = "movegen"
version = "0.1.0"
authors = ["Patrick Heck <49785565+FitzOReilly@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.0"

[dev-dependencies]
criterion = "0.3"
rand = "0.8"
perft = { path = "../perft" }

[[bench]]
name = "bench_movegen"
harness = false
